language: php

php:
  - 5.6
  - 7.0

services:
  - docker

before_install:
  - composer self-update
  - composer install -n
  - make setup-es-sandbox
  - composer cache-clear-test
  - composer setup-database-test

script:
  - composer test-ci