imports:
    - { resource: parameters.yml }

parameters:
    locale: en

framework:
    #esi:             ~
    secret:          "%secret%"
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~

es_sandbox:
    event_store_address: "%event_store_address%"