imports:
    - { resource: parameters.yml }

parameters:
    locale: en

framework:
    #esi:             ~
    secret:          "%secret%"
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: false
        naming_strategy: doctrine.orm.naming_strategy.underscore
        mappings:
            basket_projection:
                type: annotation
                dir: "%kernel.root_dir%/../src/EsSandbox/Basket/Application/Projection"
                prefix: EsSandbox\Basket\Application\Projection
es_sandbox:
    event_store_address: "%event_store_address%"